- hosts: c3725
  connection: network_cli
  gather_facts: no
  roles:
    - ansible-pyats
  tasks:
    - include_role:
        name: ansible-pyats
        tasks_from: compare_command
      vars:
        command: show ip ospf nei
        file: "{{ inventory_hostname }}_routes.json"
