---
- name: Validate Ospf with pyATS
  hosts: c3725
  connection: network_cli
  gather_facts: no
  roles:
    - role: 'roles/ansible-pyats'
  tasks:

    #- name: mise à jour des process id
    #  ios_command:
    #    commands: 'clear ip osfp process'
    #    prompt: 'Reset ALL OSPF processes? \[no\]:'
    #   answer: 'y'
        
       
    - pyats_parse_command:
        command: show ip ospf neighbor
      register: output

    - debug:
        var: output.structured
